name: MY FIRST GITHUB ACTION


on:
  push:
    branches:
        - master


env: 
  NAME: "MITESH DHRUV"
  PROFESSION: "DEVOPS ENTHUSIAST"
  PASSION: "DEVOPS ENGINEERING"


jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Echo Github Actions
         run:  echo "Hie, this is $NAME. I am a $PROFESSION by profession & $PASSION is my passion"

  post-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "echo postbuiilds steps"
        run: echo "POSTBUILDS STEPS AFTER EXECUTION OF ABOVE STEPS"
    
